# Generated by Django 5.0 on 2024-02-26 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0003_rename_college_colleges'),
    ]

    operations = [
        migrations.RenameField(
            model_name='colleges',
            old_name='College_name',
            new_name='college_name',
        ),
    ]
