# Generated by Django 5.0.1 on 2024-02-13 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('highschool', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='highschool',
            name='name',
            field=models.CharField(max_length=250, unique=True),
        ),
    ]
