# Generated by Django 5.0.2 on 2024-03-15 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_student_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='phone',
        ),
    ]
